/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#58413f',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#8c716e',
        'outline-variant': '#dfbfbc',
        'surface-tint': '#ab3332',
        'primary': '#801318',
        'on-primary': '#ffffff',
        'primary-container': '#a12c2c',
        'on-primary-container': '#ffbdb8',
        'inverse-primary': '#ffb3ae',
        'secondary': '#615e57',
        'on-secondary': '#ffffff',
        'secondary-container': '#e7e2d9',
        'on-secondary-container': '#67645d',
        'tertiary': '#735c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cca830',
        'on-tertiary-container': '#4f3e00',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3ae',
        'on-primary-fixed': '#410004',
        'on-primary-fixed-variant': '#8a1a1e',
        'secondary-fixed': '#e7e2d9',
        'secondary-fixed-dim': '#cac6be',
        'on-secondary-fixed': '#1d1c16',
        'on-secondary-fixed-variant': '#494740',
        'tertiary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#e9c349',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#574500',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
      },
      fontFamily: {
        serif: ['EB Garamond', 'serif'],
        sans: ['Be Vietnam Pro', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'container-max': '1200px',
        'gutter': '24px',
      }
    },
  },
  plugins: [],
}
